"""empty message

Revision ID: 2be8415eff94
Revises: 55f8d4c7b817
Create Date: 2014-08-19 14:42:02.379000

"""

# revision identifiers, used by Alembic.
revision = '2be8415eff94'
down_revision = '55f8d4c7b817'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
