"""empty message

Revision ID: 59407f427fe6
Revises: 4b439981e168
Create Date: 2014-08-06 23:48:07.399000

"""

# revision identifiers, used by Alembic.
revision = '59407f427fe6'
down_revision = '4b439981e168'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
